import { Container } from "../components/container";
import { Footer } from "../components/footer";
import Header from "../components/header";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta
        name="viewpoint"
        content="width=device-width, height=device-height, initial-scale-1"
      />
      <body>
        <div>
          <Header />

          <main className="pt-navigation-height">{children} </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
